resources:
  pipelines:
  - pipeline: Build
    source: Build - Policy Definitions
    trigger: true

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
   Install-Module -Name Az -AllowClobber -Scope AllUsers -Force
   
  displayName: '1. Install Az Module'


